victor_mysql:
  restart: always
  image: hub.c.163.com/library/mysql:5.6
  volumes:
    - ./conf/mysql/:/etc/mysql/conf.d
  ports:
    - "3306:3306"
  environment:
    - MYSQL_DATABASE=mysite
    - MYSQL_ROOT_PASSWORD=root


victor_web:
  restart: always
  build: .
  ports:
    - "8000:8000"
  volumes:
    - .:/website
  links:
    - victor_mysql:mysql
  command: python manage.py runserver 0.0.0.0:8000


