# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 08:07
from __future__ import unicode_literals

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=20, verbose_name='用户手机号')),
                ('name', models.CharField(max_length=10, verbose_name='中文名')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='订单号')),
                ('date', models.DateField(verbose_name='订购日期')),
                ('customer', models.CharField(max_length=20, verbose_name='入住人姓名')),
                ('phone', models.CharField(max_length=50, verbose_name='电话')),
                ('sum_price', models.IntegerField(default=0, verbose_name='订购总价')),
                ('count', models.IntegerField(default=1, verbose_name='订购数量')),
                ('begin_time', models.DateField(verbose_name='入住日期')),
                ('end_time', models.DateField(verbose_name='离店日期')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='房型库存')),
                ('type', models.IntegerField(choices=[(0, '豪华大床房'), (1, '普通大床房'), (2, '高级标准间'), (3, '普通标准间'), (4, '商务套房'), (5, '行政豪华套房'), (6, '家庭房')], default=3, verbose_name='房型类别')),
                ('desc', models.TextField(verbose_name='房型描述')),
                ('price', models.IntegerField(default=0, verbose_name='价格')),
                ('discount', models.IntegerField(default=0, verbose_name='折扣')),
            ],
            options={
                'verbose_name': '房型信息',
                'verbose_name_plural': '房型信息',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.RoomType', verbose_name='房型'),
        ),
    ]
