# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-28 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20171027_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='img',
            field=models.IntegerField(default=0, verbose_name='图片'),
        ),
    ]
