# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-28 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_roomtype_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='订单号'),
        ),
    ]
